services:
  absurd-iguana-builder:
    build:
      context: ./absurd-iguana
      dockerfile: Dockerfile
      target: base
    container_name: absurd-iguana-builder
    volumes:
      - ./absurd-iguana:/app
    working_dir: /app
    environment:
      # these must match the container names defined in this file
      - REDIS_ADDR=bashful-yak:6379
      - KAFKA_BOOTSTRAP_SERVERS=dazzling-remora:9092
  absurd-iguana:
    build:
      context: ./absurd-iguana
      dockerfile: Dockerfile
    container_name: absurd-iguana
    ports:
      - "8080:8080"
    environment:
      # these must match the container names defined in this file
      - REDIS_ADDR=bashful-yak:6379
      - KAFKA_BOOTSTRAP_SERVERS=dazzling-remora:9092
    depends_on:
      - bashful-yak
      - dazzling-remora
  bashful-yak:
    image: redis:8-alpine
    container_name: bashful-yak
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - bashful-yak-data:/data
  dazzling-remora:
    image: apache/kafka:4.2.1-rc1
    container_name: dazzling-remora
    ports:
      - "9092:9092"
    environment:
      # --- KRaft config
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@dazzling-remora:9093
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      # --- networking & network security
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      # --- cluster management
      # for a lab... this is a hardcoded uuid... IRL this would be generated
      - KAFKA_CLUSTER_ID=rVE0OBfpTCaoiapxc6mtGw
      - KAFKA_LOG_DIRS=/var/lib/kafka/data
      # --- reliability settings
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
    restart: unless-stopped
    volumes:
      - dazzling-remora-data:/var/lib/kafka/data
volumes:
  bashful-yak-data:
  dazzling-remora-data:
